import { AnimatePresence, motion } from "framer-motion";
import { BriefcaseBusiness, Check, MapPin, Search, UserPlus, X } from "lucide-react";
import type { Candidate } from "../types";

const scoreClass = (score: number) => score >= 95 ? "border-emerald-200 bg-emerald-50 text-emerald-700" : score >= 80 ? "border-amber-200 bg-amber-50 text-amber-700" : "border-red-200 bg-red-50 text-red-700";
export function MatchScore({ score }: { score: number }) { return <div className={`grid h-20 w-20 place-content-center rounded-full border-[5px] text-center ${scoreClass(score)}`}><b className="text-xl leading-5">{score}%</b><span className="mt-1 text-[9px] font-bold uppercase tracking-wide">Match</span></div>; }
export function SkillsBadges({ items, label = "Skills" }: { items: string[]; label?: string }) { return <div><p className="mb-2 text-xs font-semibold text-slate-500">{label}</p><div className="flex flex-wrap gap-1.5">{items.map((item) => <span key={item} className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-medium text-slate-600">{item}</span>)}</div></div>; }
export function EmptyState() { return <div className="panel grid min-h-80 place-items-center p-8 text-center"><div><div className="mx-auto grid h-14 w-14 place-content-center rounded-2xl bg-red-50 text-[#C1121F]"><Search className="h-7 w-7"/></div><h2 className="mt-5 text-lg font-bold">No candidates yet.</h2><p className="mt-2 text-sm text-slate-500">Upload or write a job description to begin.</p></div></div>; }
export function LoadingSkeleton() { return <div className="grid gap-4 md:grid-cols-2"><div className="h-72 animate-pulse rounded-2xl bg-slate-200"/><div className="h-72 animate-pulse rounded-2xl bg-slate-200"/></div>; }
export function AddToSelectionButton({ selected, onClick }: { selected: boolean; onClick: () => void }) { return <button onClick={onClick} className={`col-span-2 flex items-center justify-center gap-2 rounded-xl py-2.5 text-sm font-semibold transition ${selected ? "bg-red-50 text-[#C1121F] ring-1 ring-red-200" : "bg-[#C1121F] text-white hover:bg-[#A30F1A]"}`}><UserPlus className="h-4 w-4"/>{selected ? "Selected ✓" : "Add to Selection"}</button>; }
export function CandidateCard({ candidate, onView, onCustomize, selected, onSelect }: { candidate: Candidate; onView: () => void; onCustomize: () => void; selected: boolean; onSelect: () => void }) { return <motion.article layout initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} whileHover={{ y: -4 }} className="panel p-5 transition-shadow hover:shadow-xl"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-content-center rounded-xl bg-slate-900 text-sm font-bold text-white">{candidate.name.split(" ").map(x => x[0]).join("")}</div><div className="min-w-0 flex-1"><h3 className="truncate font-bold">{candidate.name}</h3><p className="mt-1 truncate text-sm text-slate-500">{candidate.role} · {candidate.company}</p></div><MatchScore score={candidate.match}/></div><div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-xs text-slate-500"><span className="flex items-center gap-1.5"><MapPin className="h-3.5 w-3.5"/>{candidate.country}</span><span className="flex items-center gap-1.5"><BriefcaseBusiness className="h-3.5 w-3.5"/>{candidate.experience} experience</span></div><div className="mt-5"><SkillsBadges items={candidate.skills}/></div><div className="mt-4"><SkillsBadges label="Languages" items={candidate.languages}/></div><p className="mt-4 border-l-2 border-[#C1121F] pl-3 text-sm leading-5 text-slate-600">“{candidate.summary}”</p><div className="mt-5 grid grid-cols-2 gap-2"><button onClick={onView} className="rounded-xl border border-slate-200 py-2.5 text-sm font-semibold transition hover:bg-slate-50">View CV</button><button onClick={onCustomize} className="rounded-xl border border-slate-200 py-2.5 text-sm font-semibold transition hover:bg-slate-50">Customize CV</button><AddToSelectionButton selected={selected} onClick={onSelect}/></div></motion.article>; }
export function CandidateModal({ candidate, onClose }: { candidate?: Candidate; onClose: () => void }) { return <AnimatePresence>{candidate && <motion.div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.div initial={{scale:.96,y:10}} animate={{scale:1,y:0}} exit={{scale:.96,y:10}} onMouseDown={e=>e.stopPropagation()} className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="label">Candidate profile</p><h2 className="mt-1 text-2xl font-bold">{candidate.name}</h2><p className="text-sm text-slate-500">{candidate.role}</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X className="h-5 w-5"/></button></div><p className="mt-6 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{candidate.summary}</p><div className="mt-6 grid gap-6 sm:grid-cols-2"><SkillsBadges label="Skills" items={candidate.skills}/><SkillsBadges label="Languages" items={candidate.languages}/><SkillsBadges label="Education" items={candidate.education}/><SkillsBadges label="Projects" items={candidate.projects}/><SkillsBadges label="Certifications" items={candidate.certifications.length ? candidate.certifications : ["None listed"]}/><div><p className="mb-2 text-xs font-semibold text-slate-500">Experience</p><p className="text-sm text-slate-700">{candidate.experience} in relevant engineering roles</p></div></div></motion.div></motion.div>}</AnimatePresence>; }
export function NotificationToast({ message }: { message?: string }) { return <AnimatePresence>{message && <motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} exit={{opacity:0,y:16}} className="fixed bottom-6 right-6 z-[60] flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-medium text-white shadow-xl"><Check className="h-4 w-4 text-emerald-400"/>{message}</motion.div>}</AnimatePresence>; }

export function SearchBar({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <div className="relative"><Search className="pointer-events-none absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={value} onChange={e=>onChange(e.target.value)} className="field w-52 pl-9" placeholder="Search candidate"/></div>; }
export function FilterBar({ sort, onSort }: { sort: string; onSort: (value: string) => void }) { return <div className="flex flex-wrap gap-2">{["Skills", "Experience", "Languages", "Country"].map(x=><button key={x} className="field text-slate-600">{x}⌄</button>)}<select value={sort} onChange={e=>onSort(e.target.value)} className="field font-medium text-slate-700"><option>Highest Match</option><option>Experience</option><option>Recently Added</option></select></div>; }
export function CVPreviewModal({ candidate, onClose }: { candidate?: Candidate; onClose: () => void }) { return <AnimatePresence>{candidate && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm" onMouseDown={onClose}><motion.div initial={{scale:.96}} animate={{scale:1}} onMouseDown={e=>e.stopPropagation()} className="w-full max-w-xl rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="label">Tailored CV preview</p><h2 className="mt-1 text-xl font-bold">{candidate.name}</h2><p className="text-sm text-slate-500">Optimized for the selected role</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X className="h-5 w-5"/></button></div><div className="mt-6 rounded-xl bg-slate-50 p-5"><h3 className="font-bold">{candidate.role}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{candidate.summary}</p><div className="mt-5"><SkillsBadges items={candidate.skills}/></div></div><div className="mt-5 flex gap-2"><button onClick={() => window.print()} className="rounded-xl bg-[#C1121F] px-4 py-2.5 text-sm font-semibold text-white">Download PDF</button><button onClick={onClose} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Done</button></div></motion.div></motion.div>}</AnimatePresence>; }
