import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { CheckSquare, Sparkles, X } from "lucide-react";
import type { Candidate } from "../types";

const ToggleList = ({ title, values, active, onChange }: { title: string; values: string[]; active: string[]; onChange: (items: string[]) => void }) => <div><p className="mb-2 text-sm font-semibold">{title}</p><div className="flex flex-wrap gap-2">{values.map(value => <button key={value} onClick={() => onChange(active.includes(value) ? active.filter(item => item !== value) : [...active, value])} className={`rounded-lg px-2.5 py-1.5 text-xs font-medium transition ${active.includes(value) ? "bg-red-50 text-[#C1121F] ring-1 ring-red-200" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{active.includes(value) && <CheckSquare className="mr-1 inline h-3.5 w-3.5"/>}{value}</button>)}</div></div>;

export function CustomizeCVModal({ candidate, onClose, onGenerate }: { candidate?: Candidate; onClose: () => void; onGenerate: (candidate: Candidate) => void }) {
  const [summary, setSummary] = useState(""); const [skills, setSkills] = useState<string[]>([]); const [experiences, setExperiences] = useState<string[]>([]); const [responsibilities, setResponsibilities] = useState<string[]>([]); const [projects, setProjects] = useState<string[]>([]); const [notes, setNotes] = useState("");
  useEffect(() => { if (candidate) { setSummary(candidate.summary); setSkills(candidate.skills); setExperiences([`${candidate.experience} at ${candidate.company}`]); setResponsibilities(["API and service delivery", "Cross-functional collaboration"]); setProjects(candidate.projects); setNotes(""); } }, [candidate]);
  return <AnimatePresence>{candidate && <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[65] grid place-items-center bg-slate-950/40 p-4 backdrop-blur-sm" onMouseDown={onClose}><motion.div initial={{scale:.97,y:10}} animate={{scale:1,y:0}} exit={{scale:.97,y:10}} onMouseDown={e=>e.stopPropagation()} className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="label">Tailored CV builder</p><h2 className="mt-1 text-2xl font-bold">Customize {candidate.name}'s CV</h2><p className="mt-1 text-sm text-slate-500">Choose the factual content to emphasize for this role.</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-slate-100"><X className="h-5 w-5"/></button></div><div className="mt-6 space-y-6"><label className="block"><span className="mb-2 block text-sm font-semibold">Edit summary</span><textarea value={summary} onChange={e=>setSummary(e.target.value)} className="min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-[#C1121F] focus:ring-4 focus:ring-red-100"/></label><ToggleList title="Select skills" values={candidate.skills} active={skills} onChange={setSkills}/><ToggleList title="Select experiences" values={[`${candidate.experience} at ${candidate.company}`, "Relevant engineering experience"]} active={experiences} onChange={setExperiences}/><ToggleList title="Select responsibilities" values={["API and service delivery", "Cross-functional collaboration", "Technical documentation"]} active={responsibilities} onChange={setResponsibilities}/><ToggleList title="Select projects" values={candidate.projects} active={projects} onChange={setProjects}/><label className="block"><span className="mb-2 block text-sm font-semibold">Notes / achievements</span><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add recruiter-approved achievements or notes..." className="min-h-20 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-[#C1121F] focus:ring-4 focus:ring-red-100"/></label></div><div className="mt-7 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600">Cancel</button><button onClick={() => onGenerate({...candidate, summary, skills, projects})} className="inline-flex items-center gap-2 rounded-xl bg-[#C1121F] px-4 py-2.5 text-sm font-semibold text-white"><Sparkles className="h-4 w-4"/>Generate Tailored CV</button></div></motion.div></motion.div>}</AnimatePresence>;
}
