import { AnimatePresence, motion } from "framer-motion";
import { Download, Search, Sparkles, X } from "lucide-react";
import type { Candidate } from "../types";
import { MatchScore } from "./CandidateUI";

const initials = (name: string) => name.split(" ").map(part => part[0]).join("");
export function GlobalEmployeeSearch({ query, onQuery, employees, onPick }: { query: string; onQuery: (value: string) => void; employees: Candidate[]; onPick: (candidate: Candidate) => void }) { const matches = query ? employees.filter(c => `${c.name} ${c.role} ${c.company} ${c.skills.join(" ")}`.toLowerCase().includes(query.toLowerCase())).slice(0, 5) : []; return <div className="relative mb-4"><Search className="pointer-events-none absolute left-4 top-3.5 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>onQuery(e.target.value)} className="field w-full pl-10" placeholder="Search all employees by name, skill, role, or company..."/>{matches.length > 0 && <div className="absolute z-30 mt-2 w-full overflow-hidden rounded-xl border border-slate-200 bg-white shadow-xl">{matches.map(candidate => <button key={candidate.id} onClick={() => { onPick(candidate); onQuery(""); }} className="flex w-full items-center gap-3 border-b border-slate-100 px-4 py-3 text-left last:border-0 hover:bg-red-50"><div className="grid h-9 w-9 place-content-center rounded-lg bg-slate-900 text-xs font-bold text-white">{initials(candidate.name)}</div><div className="min-w-0 flex-1"><p className="font-semibold">{candidate.name}</p><p className="truncate text-xs text-slate-500">{candidate.role} · {candidate.company} · {candidate.country}</p></div><span className="hidden text-xs text-slate-500 sm:block">{candidate.skills.slice(0,2).join(" · ")}</span></button>)}</div>}</div>; }

export type ActiveFilters = Record<string, string>;
const choices: Record<string, string[]> = { Skills: ["Python", "Kubernetes", "Docker", "React"], Experience: ["4+ years", "5+ years", "7+ years"], Languages: ["English", "French", "Arabic"], Country: ["Tunisia", "France", "Morocco", "Canada"], Position: ["Python Engineer", "Platform Engineer", "Full Stack Engineer"], Company: ["Nexa Cloud", "Octave Systems", "Atlas Digital", "Northstar Labs"] };
export function AdvancedFilters({ active, onChange, sort, onSort }: { active: ActiveFilters; onChange: (filters: ActiveFilters) => void; sort: string; onSort: (value: string) => void }) { return <div className="flex flex-wrap gap-2">{Object.entries(choices).map(([label, values]) => <select key={label} value={active[label] || ""} onChange={e => onChange({...active, [label]: e.target.value})} className="field max-w-40 text-slate-600"><option value="">{label}</option>{values.map(value => <option key={value}>{value}</option>)}</select>)}<select value={sort} onChange={e=>onSort(e.target.value)} className="field font-medium text-slate-700"><option>Highest Match</option><option>Experience</option><option>Recently Added</option></select></div>; }

export function SelectedCandidatesPanel({ candidates, onRemove, onGenerate, onExport }: { candidates: Candidate[]; onRemove: (id: string) => void; onGenerate: () => void; onExport: () => void }) { return <section className="panel mb-7 overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><p className="label">Recruiter shortlist</p><h2 className="mt-1 text-xl font-bold">Selected Candidates</h2></div><span className="rounded-full bg-red-50 px-3 py-1 text-xs font-bold text-[#C1121F]">{candidates.length} selected</span></div><div className="p-4"><AnimatePresence initial={false}>{candidates.length === 0 ? <p className="py-4 text-sm text-slate-500">No candidates selected yet.</p> : <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-3">{candidates.map(candidate => <motion.div key={candidate.id} layout initial={{opacity:0, scale:.96}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.96}} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3"><div className="grid h-9 w-9 place-content-center rounded-lg bg-slate-900 text-xs font-bold text-white">{initials(candidate.name)}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{candidate.name}</p><p className="truncate text-xs text-slate-500">{candidate.role}</p></div><span className="text-sm font-bold text-[#C1121F]">{candidate.match}%</span><button onClick={() => onRemove(candidate.id)} className="rounded-md p-1 text-slate-400 hover:bg-red-50 hover:text-[#C1121F]" aria-label={`Remove ${candidate.name}`}><X className="h-4 w-4"/></button></motion.div>)}</div>}</AnimatePresence></div><footer className="flex flex-col gap-3 border-t border-slate-100 bg-slate-50 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-medium text-slate-600">Total selected: {candidates.length}</span><div className="flex gap-2"><button onClick={onExport} disabled={!candidates.length} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-semibold disabled:opacity-40"><Download className="h-4 w-4"/>Export Selection</button><button onClick={onGenerate} disabled={!candidates.length} className="inline-flex items-center gap-2 rounded-xl bg-[#C1121F] px-3 py-2 text-sm font-semibold text-white disabled:opacity-40"><Sparkles className="h-4 w-4"/>Generate Tailored CVs</button></div></footer></section>; }
